version: '3'

services:
  api-jwt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - apijwt-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - apijwt-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - apijwt-network

networks:
  apijwt-network:
