version: '3'

services:
  api-jwt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - minha-rede

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - minha-rede

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - minha-rede

networks:
  minha-rede:
